name: Checks PR changes
on:
  workflow_dispatch:
    inputs:
      owner:
        required: true
      name:
        required: true
      pr_number:
        required: true
jobs:
  check-pr-changes:
    name: Check PR changes
    runs-on: ubuntu-latest
    steps:
      - name: Check PR changes step
        id: check-pr-changes-step
        uses: L-Sypniewski/github-pr-changes-checker-action@master
        with:
          owner: ${{ github.event.inputs.owner }}
          name: ${{ github.event.inputs.name }}
          pr_number: ${{ github.event.inputs.pr_number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print output
        run: |
            echo '${{ steps.check-pr-changes-step.outputs.updated-projects }}'
